CREATE TABLE wx_callback_route (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    uuid VARCHAR(64) NOT NULL COMMENT '企微运行实例 UUID',
    callback_url VARCHAR(1024) NOT NULL COMMENT '业务系统回调 URL',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_uuid (uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='企微员工业务系统回调路由';
