#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Apr 13 00:01:10 CST 2026
maven-metadata-2562881-snapshot-bNxTDV.xml.error=
maven-metadata-snapshots.xml.lastUpdated=1776009670568
maven-metadata-2562881-snapshot-bNxTDV.xml.lastUpdated=1776009670572
maven-metadata-snapshots.xml.error=
